eccomerce_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='home'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/update_item/', views.updateItem, name='cart_update_item'),
    path('process_order/', views.processOrder, name='process_order')
]

store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=300, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping


    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property 
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True, related_name='shipping_addresses')
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True, related_name='shipping_addresses')
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
   
    
    def __str__(self):
        return self.address


    

store/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .utils import cookie_cart, cart_data, guest_order
from . import models
import json
import datetime
# Create your views here.
def store(request):
    data = cart_data(request)
    cartItems = data['cartItems']

    products = models.Product.objects.all()
    context = {'products': products, 'cartItems': cartItems, 'shipping': False}
    return render(request, 'store/store.html', context)


def cart(request):
    data = cart_data(request)
    cartItems = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cartItems, 'shipping': False}
    return render(request, 'store/cart.html', context)


def checkout(request):
    data = cart_data(request)
    cartItems = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cartItems, 'shipping': False}
    return render(request, 'store/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print ('Action: ', action)
    print ('Product id: ', productId)

    customer = request.user.customer
    product = models.Product.objects.get(id=productId)
    order, created = models.Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = models.OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <=0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = models.Order.objects.get_or_create(customer=customer, complete=False)

    else:
        order, customer = guest_order(request, data)
    
    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        models.ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
    )
    return JsonResponse('Payment Complete', safe=False)

store/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a href="{% url 'store:home' %}" class="btn btn-outline-dark">&#x2190; Continue Shopping</a>
                <br>
                <br>
                <hr>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>₹{{order.get_cart_total}}</strong></h5></th>
                        <th>
                            <a href="{% url 'store:checkout' %}" class="btn btn-success" style="float: right; margin: 5px;">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>
            <br>
        </div>

        <div class="col-lg-12">
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Prince</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img src="{{item.product.imageURL}}" class="row-image"></div>
                        <div style="flex:2">{{item.product.name}}</div>
                        <div style="flex:1">₹{{item.product.price}}</div>
                        <div style="flex:1">
                            <p class="quantity">{{item.quantity}}</p>
                            <div class="quantity">
                                <img  data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
                        
                                <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}" >
                            </div>
                        </div>
                        <div style="flex:1">₹{{item.get_total}}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

store/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">
                <form id="form">
                    {% csrf_token %}
                    <div id="user-info">
                        <div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
                    </div>

                    <div id="shipping-info">
                        <hr>
                        <p>Shipping Information:</p>
                        <hr>			
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
                    </div>

                    <hr>

                    <input id="form-button" type="submit" value="Continue" class="btn btn-success">
                </form>

            </div>

            <br>
            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
                <button id="make-payment" class="btn btn-primary">Make Payment</button>
            </div>
        </div>
        
        <div class="col-lg-6">
            <div class="box-element">
                <a  class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                    <div class="cart-row">
                        <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                        <div style="flex:2"><p>{{item.product.name}}</p></div>
                        <div style="flex:1"><p>₹{{item.product.price}}</p></div>
                        <div style="flex:1"><p>{{item.quantity}}</p></div>
                    </div>
                {% endfor %}
            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: ₹{{order.get_cart_total}}</h5>
            </div>
        </div>
    </div>
<script type="text/javascript">
    var shipping = "{{order.shipping}}"
    var total = '{{order.get_cart_total|floatformat:2}}'
    var user = '{{user}}'
    if (shipping == 'False'){
        document.getElementById('shipping-info').innerHTML = ''
    }

    if (user != 'AnonymousUser'){
        document.getElementById('user-info').innerHTML = ''
    }
    if (shipping == 'False' && user != "AnonymousUser"){
        document.getElementById('form-wrapper').classList.add("hidden")
        document.getElementById('payment-info').classList.remove('hidden')

    }
    var form = document.getElementById('form')
    csrftoken = form.getElementsByTagName('input')[0].value
    form.addEventListener('submit', function(e){
        e.preventDefault()
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    })

    document.getElementById('make-payment').addEventListener('click', function(e){
        submitFormData()
    })

    function submitFormData(){
        console.log('Payment button clicked')
        var userFormData = {
            'name': null,
            'email': null,
            'total': total,

        }
        var shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null
            
        }

        if (shipping != 'False'){
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        
        if (user == 'AnonymousUser'){
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        var url = '/process_order/'
        fetch(url, {
            method: "POST",
            headers:{
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
            body: JSON.stringify({'form': userFormData, 'shipping': shippingInfo})
        })
        .then((response) => response.json())
        .then((data)=>{
            console.log("Success: ", data);
            alert("Transaction Complete")
            cart = {}
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
            window.location.href = '{% url "store:home" %}'
        })
    }
</script>
{% endblock %}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ecommerce Website</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script type="text/javascript">
    var user = '{{request.user}}'

    function getToken(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
  var csrftoken = getToken('csrftoken');

  function getCookie(name){
    var cookieArr = document.cookie.split(";")

    for(var i = 0; i < cookieArr.length; i++){
      var cookiePair = cookieArr[i].split('=')

      if (name == cookiePair[0].trim()){
        return decodeURIComponent(cookiePair[1]);
      }
    }
    return null;
  }
  var cart = JSON.parse(getCookie('cart'))
  if(cart == undefined){
    cart = {}
    console.log('cart was created')
    document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
  }
  console.log('cart: ', cart)

  </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'store:home' %}">Ecommerce</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Store</a>
              </li>
            </ul>

            <div class="form-inline my-2 my-lg-0">
              <a href="#" class="btn btn-warning">Login</a>
              <a href="{% url 'store:cart' %}" class="cart-link">
                  <img src="{% static 'images/cart.png' %}" id="cart-icon">
              </a>
              <p id="cart-total">{{cartItems}}</p>
            </div>
          </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</html>

store/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
        <div class="row">
            {% for product in products %}
                <div class="col-lg-4">
                    <img src="{{product.imageURL}}" alt="product_image" class="thumbnail">
                    <div class="box-element product">
                        <h6><strong>{{product.name}}</strong></h6>
                        <hr>
                        <button data-product="{{product.id}}" data-action='add' class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                        <a href="#" class="btn btn-outline-success">View</a>
                        <h4 style="float: right;"> ₹{{product.price|floatformat:2}}</h4>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}